
- hosts: netscaler
  gather_facts: no
  vars:
    filename: "ns.conf"
    filelocation: "/var/tmp"
    localfile: "/var/tmp/ns.conf"

  tasks:
    - name: Put file
      delegate_to: localhost
      uri:
        url: "http://{{ nsip }}/nitro/v1/config/systemfile"
        method: POST
        status_code: 201
        return_content: yes
        headers:
          X-NITRO-USER: "{{ nitro_user }}"
          X-NITRO-PASS: "{{ nitro_pass }}"
        body_format: json
        body:
          systemfile:
            filename: "{{ filename }}"
            filecontent: "{{ lookup('file', localfile) | b64encode }}"
            filelocation: "{{ filelocation }}"
