- hosts: netscaler
  gather_facts: no
  vars:
    feature_action: enable
    request_payload:
      nsfeature:
        feature:
          - LB

  tasks:

    - name: Enable NS feature
      delegate_to: localhost
      uri:
        url: "http://{{ nsip }}/nitro/v1/config/nsfeature?action={{ feature_action }}"
        method: POST
        status_code: 200
        headers:
          X-NITRO-USER: "{{ nitro_user }}"
          X-NITRO-PASS: "{{ nitro_pass }}"
        return_content: yes
        body_format: json
        body: "{{ request_payload }}"
