
- hosts: netscaler
  gather_facts: no
  vars:
    login_object:
      login:
        username: "{{ nitro_user }}"
        password: "{{ nitro_pass }}"

    managed_instance_ip: 10.221.48.207

    filename: "ns.conf"
    filelocation: "/var/tmp"
    localfile: "/var/tmp/ns.conf"

  tasks:
    - name: MAS Login
      register: login_result
      delegate_to: localhost
      uri:
        url: "http://{{ nsip }}/nitro/v1/config/login"
        method: POST
        return_content: yes
        status_code: 200
        body_format: json
        body: >
          object=
          {{ login_object | to_json }}
    - name: Put file
      delegate_to: localhost
      uri:
        url: "http://{{ nsip }}/nitro/v1/config/systemfile"
        method: POST
        status_code: 201
        return_content: yes
        headers:
          Cookie: "NITRO_AUTH_TOKEN={{ login_result.json.login[0].sessionid }}"
          _MPS_API_PROXY_MANAGED_INSTANCE_IP: "{{ managed_instance_ip }}"
        body_format: json
        body:
          systemfile:
            filename: "{{ filename }}"
            filecontent: "{{ lookup('file', localfile) | b64encode }}"
            filelocation: "{{ filelocation }}"
