- hosts: netscaler

  gather_facts: no

  vars:
    filename: "ns.conf"
    filelocation: "/var/tmp"

  tasks:
    - name: Delete old ns.conf
      delegate_to: localhost
      uri:
        url: "http://{{ nsip }}/nitro/v1/config/systemfile?args=filename:{{ filename }},filelocation:{{ filelocation | replace('/','%2F') }}"
        method: DELETE
        status_code: 200
        return_content: yes
        headers:
          X-NITRO-USER: "{{ nitro_user }}"
          X-NITRO-PASS: "{{ nitro_pass }}"
