
- hosts: netscaler
  gather_facts: no
  vars:
    resource: server/test-server-1

  tasks:
    - name: Get resource
      delegate_to: localhost
      uri:
        url: "http://{{ nsip }}/nitro/v1/config/{{ resource }}"
        method: GET
        status_code: 200
        return_content: yes
        headers:
          X-NITRO-USER: "{{ nitro_user }}"
          X-NITRO-PASS: "{{ nitro_pass }}"
